### ISSUE TITLE
Can't "Delete Settings"

### ISSUE THREAD

**Issue by TrainerMerch** [facebookincubator/facebook-for-woocommerce#1001]
I am having an issue a where I try to "Delete Settings" in "Advanced Options" and it says "Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later."

My FB Page is:
https://www.facebook.com/TrainerMerch/

My website is:
https://trainermerch.com

My Pixel ID is:
313644459235602

**Comment by jacobabey1** [comment]
Facing this same issues .

**Comment by Filoz** [comment]
same issue

**Comment by guibarbas** [comment]
same issue

**Comment by adkinzd** [comment]
I am also having this issue . Can you let me know what you need me to do?

Our FB Page is...

https://www.facebook.com/Oncanvaswallart-1235158439964917/?modal=admin_todo_tour

Our website is...

https://oncanvaswallart.com/

Our Pixel ID: 219562232320699

**Comment by sushmaad** [comment]
This issue has been fixed, can you retry.

**Comment by TrainerMerch** [comment]
@sushmaad 
I have just tried to delete the settings and still get the same error.

**Comment by nguyenanh17** [comment]
<img width="755" alt="Screen Shot 2019-05-24 at 18 29 14" src="https://user-images.githubusercontent.com/34606151/58324734-e8851f80-7e51-11e9-8eb2-cbdd5a064ba9.png">
Same issue.
I still can not "delete setting". Could you please fix it ?

**Comment by TrainerMerch** [comment]
I am now able to delete my settings. Thank you.

**Comment by jeffsandoval014** [comment]
I can't delete settings because I can't open the Settings page. :(

**Comment by adkinzd** [comment]
Thank you

jeffsandoval014 <notifications@github.com> 于2019年9月15日周日 下午11:07写道：
