### ISSUE TITLE
Cant Link or Unlink my existing Facebook Page

### ISSUE THREAD

**Issue by fcarsenal12** [facebookincubator/facebook-for-woocommerce#1010]
Hi , my page was already linked but got a problem after deleting the main catalogue
. now i cant even Link or unlink the page again to the plugin Facebook for Woocommerce.
and got this error.
 "Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later."
![Screen Shot 2019-05-23 at 04 05 19](https://user-images.githubusercontent.com/42844129/58225176-63462180-7d10-11e9-8346-4d98f134f13e.png)
![Screen Shot 2019-05-23 at 04 05 34](https://user-images.githubusercontent.com/42844129/58225198-722cd400-7d10-11e9-85b8-c1cde842e9df.png)

I use latest version version :  View version 1.9.12

my facebook page : [https://www.facebook.com/laqcompany/](url)
website : [https://laq.co.ma](url)

**Comment by segal77** [comment]
I have the same problem.. I am interested too, how it possible to solve it. :)

**Comment by morethanwords1980** [comment]
Same problem, 
Duplicate of #998

**Comment by fcarsenal12** [comment]
I just dont know why there is no support for this plugin . We cant now use facebook shop for woocommerce

**Comment by jacobabey1** [comment]
https://developers.facebook.com/community/threads/1066316133570771/

**Comment by sushmaad** [comment]
"Something went wrong" Issue has been fixed, can you please retry.

**Comment by fcarsenal12** [comment]
> "Something went wrong" Issue has been fixed, can you please retry.

problem is still there , i still got same message when i try to remove settings of my exsiting page to link it again https://www.facebook.com/laqcompany/
, even if i reinstalled n reseting plugin in my website

**Comment by ristyawank** [comment]
> "Something went wrong" Issue has been fixed, can you please retry.

problem is still there

**Comment by jacobabey1** [comment]
@sushmaad  , the issue isn't fixed , its still pending

**Comment by nguyenanh17** [comment]
same issue

**Comment by Joaoaso** [comment]
I have the same problem.. I am interested too, how it possible to solve it. :)

**Comment by Licto** [comment]
Same problem...

**Comment by diwangcmu** [comment]
According to #998 this issue should have been resolved. Can you retry and see if the problem persists? Thanks!
