### ISSUE TITLE
Deleted products still show up on Facebook

### ISSUE THREAD

**Issue by Smyckendahls** [facebookincubator/facebook-for-woocommerce#1151]
Products that have been deleted in our WooCommerce shop still show up in Facebook shop. How can we remove them? Please note that they have been completely removed, and we cannot go back and click in the option "Delete product(s) on Facebook" or unmark Visible.

**Comment by scoobynko** [comment]
same problem, and sync doesn't help at all.

**Comment by Pedro-calvo-lopez** [comment]
Morning,
When you remove a product from woocommerce, it is not completely removed. Once deleted, you have to go to the trash can where the products are still stored. You will have to empty the bin and from there you will see that your deleted products disappear from the Facebook store. Good luck

**Comment by Smyckendahls** [comment]
Hi Pedro, thank you for trying to help. 

The problem is that the products showing up in our Facebook shop are NOT still in the trash. They have been removed from the back-end and the bin has been permanently emptied but the products still appear on Facebook. Since they are no longer in the bin it is impossible to delete them again, or hide their visibility from Facebook. These products have been deleted permanently a long time ago, in many cases several months ago, so it’s not a time-lag/sync issue.

Kind regards
Caroline

Caroline Lannerup
E Commerce Manager
Smyckendahls AB
Åsögatan 176
116 32 Stockholm

caroline@smyckendahls.se

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by Smyckendahls** [comment]
Hi Lindsey,

we have the Version 1.10.2. I’m not sure if there is a newer version?

The problem still remains. Also, we find that lots of products that are temporarily out of stock still show up in the Facebook shop. I suspect that both these issues have something to do with the feed not being read properly by Facebook? 

Vänliga hälsningar
Caroline

Caroline Lannerup
E Commerce Manager
Smyckendahls AB
Åsögatan 176
116 32 Stockholm
+46 8 20 44 40
+46 70 41 31 151
caroline@smyckendahls.se

**Comment by Tjerk-Haaye-Henricus** [comment]
I have the same problem
