### ISSUE TITLE
Delete products from catalog & shop: Incompatibility with Advanced Bulk Edit plugin

### ISSUE THREAD

**Issue by metuza** [facebookincubator/facebook-for-woocommerce#141]
I have a while ago deleted some products from my webshop and these products still appear in FB shop, catalog and ads. Is it possible somehow to delete these products without re-setting the entire catalog?

I have done several forced product syncs with no luck, the products still appear in ads.

Thanks

**Comment by tahoff** [comment]
Hello @metuza, thanks for flagging. This looks like the same issue reported in #75, unfortunately it's still unresolved.

**Comment by dmitridr** [comment]
@metuza Thanks again for reaching out to us with these issues. Can you go into details and give us specific steps about how you deleted these products so that we can reproduce the problem? If I delete products individually on our test servers these are deleted from our test shop, so we cannot currently reproduce the problem.

**Comment by metuza** [comment]
Hello @dmitridr - I guess that this actually is not a issue, i am just missing an option in the catalog OR the shop to delete products ;) .. I know from earlier if i manually added products to the FB shop then i was also able to delete them.

My problem is most probably that i have forgot to delete these products from FB in the product editor of WooCommerce before i deleted them from my webshop. I guess that is why they still appear in FB catalog and shop after i deleted them from my webshop.

So by now i guess that i just have to reset my catalog and fb shop to get these products deleted.

Sorry if i was unclear in this.

**Comment by dmitridr** [comment]
I see, thanks for the clarification. Could you explain more about how you deleted it from your webshop without using the WooCommerce product editor? is there some other deletion area our plugin should hook into? 

Yes, unfortunately the only full workaround is to reset.
For ads specifically there could be a partial workaround, by excluding those manually from any product sets you are using to advertise.

I will mark this as a feature request for a delete button on the shops side. But it would probably be easier for our plugin to delete the product if you delete the page from your webshop (if that is possible).

**Comment by metuza** [comment]
Well most probably i have just moved the product to the trash from the product overview/listing page, then it has been deleted on my weekly DB clean-up. Sometimes i have also used the WooCommerce Advanced Bulk Edit plugin bought at Envato market.

But now i do delete the product from FB when product opened up in product editor - then i delete the product :) Seems to work great..

**Comment by thierrymaasdam** [comment]
Can confirm this issue as well. Got complaints from two clients as well.

**Comment by Vezzian** [comment]
I'm having the same issue. I created some demo products manually before installing the plugin. The plugin imported the demo products to my FB page's shop. Realizing this I manually deleted the products before i realized i should have removed them via the plugin itself. The products no longer exist on my website, but they still exist in my FB shop and I can't find a way to remove them. Please help!

**Comment by mengyingdu** [comment]
Hi @metuza ,

We support trash/restore in [v1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0) which also added many features/fixes, can you try to upgrade?

Thanks!

**Comment by mengyingdu** [comment]
Hi @Vezzian and @thierrymaasdam,


Here are some workround:
We fixed trash/restore in [v1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0) which also added many features/fixes, can you try to upgrade?

Also, can you try to Re-configure Facebook Settings (which should in WooCommerce settings->integrations->Facebook for WooCommerce? It should reset your Facebook shop.

**Comment by Vezzian** [comment]
Thank you! 




I was able to reconfigure the settings which fixed my issues. 




Simon Yates | tees2seize.com







From: mengyingdu


Sent: Wednesday, November 29, 2:53 PM


Subject: Re: [facebookincubator/facebook-for-woocommerce] Delete products from catalog & shop (#141)


To: facebookincubator/facebook-for-woocommerce


Cc: Vezzian, Mention






Hi @Vezzian and @thierrymaasdam,


Here are some workround:


We fixed trash/restore in v1.7.0 which also added many features/fixes, can you try to upgrade?


Also, can you try to Re-configure Facebook Settings (which should in WooCommerce settings->integrations->Facebook for WooCommerce? It should reset your Facebook shop.

**Comment by planetpopc** [comment]
Hi there, i have the same problem, and absolutely struggling to make sense of it all. I had products that were either hidden, private, or in trash, and they still show up in Facebook store. I have now also deleted the items form the trash ( which i did not want to do ), and they still show up in on the Facebook store.

**Comment by mengyingdu** [comment]
Hi @planetpopc ,

What's your plugin version? We have better support for visibility and trashing after v1.7.0 and now the latest version is [1.7.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.3). Can you upgrade and then force-resync? It should resolve your problem.

Let me know if you need more help.

Thanks.

**Comment by grabrail** [comment]
Hi, I am also having this issue, I am on version 1.7.3 and have resynced but my "deleted" products still appear on my FB page, with no way to manually delete them

**Comment by dmitridr** [comment]
Thanks for reporting. That's weird because I thought we fixed the trashing of products in 1.7.3 or earlier. Maybe those products were trashed a while back before we fixed trashing? 

Trashing should mark the product as invisible on FB, so you will still see them but the customer won't, and there should be a big notice saying that the product is invisible, just tested it out on the latest version.

**Comment by mengyingdu** [comment]
Hi @grabrail,

Is this problem still occur to you? If so, can you open a new issue to help us track your problems? Since this should have been fixed in 1.7.3. 

Thanks.

**Comment by grabrail** [comment]
@mengyingdu 

All good for me now thanks, turned out to be an issue on the FB Catalog side not with the plugin

**Comment by dmitridr** [comment]
We implemented basic support for `Advanced Bulk Edit` in v1.9.8. Check it out. 
Basic support means after you use the bulk edit on products, you'll get a notification that your products need to be resynced and a helpful link to do so.
