### ISSUE TITLE
Facebook upgrade crashes

### ISSUE THREAD

**Issue by snowloversglobal** [facebookincubator/facebook-for-woocommerce#1443]
I have just updated the Facebook plugin and when I click to reconnect it comes up with a error try refreshing your page. Any word on a patch or fix for this?

**Comment by raejin** [comment]
I'm also running into this issue, there is very little log which suggests how to fix this issue.

**Comment by srpf** [comment]
I have this issue too.

**Comment by PrintedInWood** [comment]
I have the same issue. I have also had an issue where I get through to configure it, and then it tells me my advertising maximum has been reached so I should make a payment to fix this before I can continue. My account is at £0 at the moment as I haven't been advertising!
![Woo Commerce Problem](https://user-images.githubusercontent.com/64734002/89120007-66a77200-d4aa-11ea-9888-6d92f08b4730.jpg)

**Comment by lgfogle** [comment]
Hey @snowloversglobal, @raejin, @srpf, and @PrintedInWood,

Thanks for letting us know about this problem! I'm sorry about these reconnection issues - we reported these to Facebook last week and they have released an update (not to the plugin, but to the connection wizard on Facebook's end) that should resolve this problem.

Could you please try connecting again and let me know if you're still encountering this issue?

Thank you!
Lindsey

**Comment by raejin** [comment]
@lgfogle 
The issue is fixed now. Appreciate the update!

**Comment by PrintedInWood** [comment]
Hi Lindsey, 
I tried again and I’m still getting the same issue
Thanks,
Liz


Find us at Printed In Wood 
Follow us on Facebook

**Comment by snowloversglobal** [comment]
Hi Lindsay. Sorry to saw. This has not fixed the issue. 

Peter Hosking

Sent from my iPhone

On 4 Aug 2020, at 1:37 am, Lindsey Fogle <notifications@github.com> wrote:

﻿
Hey @snowloversglobal, @raejin, @srpf, and @PrintedInWood,

Thanks for letting us know about this problem! I'm sorry about these reconnection issues - we reported these to Facebook last week and they have released an update (not to the plugin, but to the connection wizard on Facebook's end) that should resolve this problem.

Could you please try connecting again and let me know if you're still encountering this issue?

Thank you!
Lindsey

**Comment by lgfogle** [comment]
Hey @PrintedInWood and @snowloversglobal,

The Facebook team has released more fixes on their end that may resolve this issue - could you please try again and let me know if that works? There are a few pending problems that they are still working hard to address, but wanted to see if the work they've already done has fixed the particular problem that was blocking your connection.

Thank you!
Lindsey

**Comment by PrintedInWood** [comment]
Hi Lindsey,
Yes, it has all been setup now. Thanks for the follow up!
Kind regards
Liz


Find us at Printed In Wood 
Follow us on Facebook

**Comment by lgfogle** [comment]
Great news, @PrintedInWood! Thanks for your patience. 

@snowloversglobal, I'm going to close this issue, but could you please respond here if you're still seeing connection errors? I can then reopen the issue and continue troubleshooting. 

Thanks everyone!
