### ISSUE TITLE
Not possible to connect a store through a partnered connection in Facebook Business Manager

### ISSUE THREAD

**Issue by jbaekz** [facebookincubator/facebook-for-woocommerce#1453]
Hi, 

After updating to the latest version (2.0.0) I found an issue.

Not sure if this is a bug or designed to work as it is.

The problem is that we administrate different online stores and our company is connected through the "partner" function in Facebook Business Manager to the FB pages/businesses that we cowork with. 

It seems that we cannot connect the online stores to Facebook (with your plugin) when trying on pages connected through the partner function. 

I did a test and we can connect to FB pages/businesses if we are added directly as an admin on the specific FB page/business. 

So my question is: Do we have to be added as and admin directly on each FB business that we want to connect to the online store? 
Alternatively we have to remote control our clients computer and set up the integration directly on their Facebook login.

If this is the case it kind of eliminates the idea of using the partner function in Facebook Business Manager. 

I hope it makes sense. Otherwise please feel free to ask for more information. :) 

Kind regards
Jacob

**Comment by lgfogle** [comment]
Hey @jbaekz,

Thanks for reaching out!

This is a great question, but one that we'll need to communicate with Facebook to answer since they control the business extension side. I'll reach out to their team about this issue and follow up once I know more!

Thank you,
Lindsey

**Comment by lgfogle** [comment]
[Direct support ticket for internal reference](https://business.facebook.com/direct-support/question/319723402512007/?force_full_site=0&business_id=808073152608315)

**Comment by tnchuntic** [comment]
Any update on this issue. I am encountering this issue also. Its a bit weird because of user have been assign already as admin in both page, catalog, pixel and business manager through business asset group. 
But still couldn't connect to the following:
- page its visible but not selectable.
- pixel not visible at all.

**Comment by maplehoney** [comment]
We're having the same issue.  Our agency is unable to connect any Facebook assets through this plugin as all pages, ad accounts and such are appearing as "Not Eligible".  We have 35 sites affected and product catalogues are no longer being updated.  We've had to use 3rd party plugins to keep things working - would ideally prefer this to be fixed so we can continue to use this instead.

**Comment by lgfogle** [comment]
Hey @jbaekz, @tnchuntic, and @maplehoney,

Thanks for your patience, my apologies for the delay!

I've been in touch with the Facebook support team, and they've said that as long as your agency access provides an admin level of access to these assets (which clients can specify when setting up the agency access), you should be able to select them in the Facebook for WooCommerce onboarding. 

Could you please confirm whether you have agency access to all assets you're trying to select? If you can confirm this, could you please also share a screenshot of the exact error you're seeing so I can share that with Facebook?

Thanks!
Lindsey

**Comment by jbaekz** [comment]
Hey @lgfogle, 

Confirming that we have agency access to all assets with top level (admin) rights granted. 
I know this because we always help our clients setting up the partner access, so it's me who set the rights for the partner access assets initially.

To me it looks consistent to be a problem on all agency access setups. 
As mentioned earlier I've been doing some testing by adding myself as an admin directly on some of the FB Business Manager accounts and thereby bypassing the agency access function. 

Attached picture of the error. 
It's hard to see, but the pages (that I discretely blurred out..) are faded/grayed out so they can't be chosen.
Error description is visible. 

![image](https://user-images.githubusercontent.com/33039746/92305752-63604400-ef8a-11ea-9e05-98b67fe7ea98.png)


Please let me know if you need anything else. Happy to contribute!
Jacob

**Comment by lgfogle** [comment]
Hey @jbaekz,

Thanks for following up! I'll share that information with the Facebook team and see what they think. I'll be in touch once I hear back - thanks for sharing that info with me!

Lindsey

**Comment by jbaekz** [comment]
Hi @lgfogle, 

Sorry for the late response!

Please find information here:
https://quickforget.com/s/96a502c1a125b083f71862609eb32208d664355e8e239618

Also be aware that I had to add myself directly as an admin to this page. 
So right now I'm connected through the agency access AND directly as an admin on the business account. 


Kind regards
Jacob

**Comment by lgfogle** [comment]
Hey @jbaekz,

I am so sorry for the delay - I was out of the office and missed the expiration on this QuickForget! Could you please send that again and I'll pass that information along to Facebook?

Thanks!
Lindsey

**Comment by jbaekz** [comment]
@lgfogle,

Here's the information: https://quickforget.com/s/ebf60539c559e2081e04fa47554f69309ee66462e2fcd1d6 

Kind regards
Jacob

**Comment by lgfogle** [comment]
Hey @jbaekz,

Thanks for sharing that information! I've viewed the secret enough times that it's been forgotten. I passed that information along to Facebook support, so I will follow up once I know more!

Thank you,
Lindsey

**Comment by simonporter007** [comment]
Hey @jbaekz,

Thanks for your patience so far. We've been working with Facebook on a few different permission issues which they have released fixes for. I am not sure if the issue you're describing is now resolved along with these, however, so it would be great if you could test the connection with the latest version and let me know!

The screen your referencing appears in the Facebook Business Extension API that we unfortunately don't have a view of. If you're still seeing the same issues for your agencies managed businesses, my recommendation would be to reach out to the Facebook support team directly so that they can take a closer look at one of these particular businesses. [This contact form](https://www.facebook.com/help/contact/552096935652452) should then pre-populate with the relevant ID's for them to see the business manager settings too.

In the meantime though, I'd love to hear if the recent fixes their team released has worked! Could you let me know?

Cheers!

**Comment by jbaekz** [comment]
Hi @simonporter007, 

I can confirm that it is still not working. 

What works right now is to directly add users as admins to the Facebook Business Manager eliminating the use of the Partner function. This does come with some other issues but it seems like the best temporary solution right now.

Kind regards

**Comment by coccoinomane** [comment]
Hi,
The connection works fine with v1.10.2 of the plugin. Why not just switching back to the old authentication method? We could all die of old age waiting for Facebook to fix the problem.
Guido

**Comment by coccoinomane** [comment]
Is there any workaround to this issue? Maybe another plugin while it is fixed? Thank you

**Comment by coccoinomane** [comment]
Hi, is there any update on this issue?
Thank you.

**Comment by coccoinomane** [comment]
Hello, any news on this matter?
As of today it still does not work and, worse of all, the plugin does not explains why, leaving the user to wonder why.
Thank you,
Guido

**Comment by OmarFPG** [comment]
8273582-zen
