### ISSUE TITLE
Primary images on Facebook shop not matching the primary images on WooCommerce

### ISSUE THREAD

**Issue by chalkandmoss** [facebookincubator/facebook-for-woocommerce#231]
Hello, I wonder if you can help. The image order of the products being bought into facebook from woocommerce doesn't appear to correlate correctly. This is particularly true of products where there are multiple variants, when the variant image is selected. Ideally I would like the 'featured image' from woocommerce to be the first image in facebook. this doesn't seem to be the case. Is it possible to solve this somehow, or is there a way of managing and re-ordering the images for each product when they are in the facebook shop? Many thanks, Anna

**Comment by chalkandmoss** [comment]
The issue with Facebook showing an image from a variation is that it shows an image of the wood type instead of the whole product (ie if an item is available in 4 wood types).
As well as the logic of how Facebook chooses which image to display, I also can't work out how it selects which price to show. Woocommerce displays the cheapest price on the cover of a variable product, but I can't see a pattern for which price Facebook displays (e.g. if something's available in small, medium, large).

This is an item from my website:
https://www.chalkandmoss.com/product/wooden-candle-holders-mima/

And the same item on the Facebook shop:
https://www.facebook.com/commerce/products/1838956082843173/

**Comment by chalkandmoss** [comment]
I've just noticed another key piece of this puzzle. If you look at the facebook shop in the browser on an iPhone, it displays the product feature image correctly, the same as on chalkandmoss.com. But on desktop browser and the facebook app it seemingly chooses an image from product variations at random to display!

**Comment by sammul** [comment]
@chalkandmoss thanks for the feedback and sorry the primary images are not what you expected. We will look into more deeply and try to resolve this in next versions.

**Comment by chalkandmoss** [comment]
Here are screenshots from the desktop browser and facebook app, where images are not displaying feature images, but instead a variation image. But there doesn't seem to be a pattern as to what image it selects (sometimes 2nd, sometimes 5th etc). There's also a screenshot from the iPhone browser, where it DOES correctly pull the feature image from WooCommerce. 

NOTE: The same issue happens with pricing. WooCommerce displays the lowest price for variable products (e.g. where small, medium and large are available for vases). But on the Facebook shop, it seems to choose the price at random, which will confuse shoppers. Sometimes it's the lower price, sometimes the higher. 

![app](https://user-images.githubusercontent.com/35746921/35359204-17a83a88-0151-11e8-9085-d9421cf28376.jpg)
![desktop browser](https://user-images.githubusercontent.com/35746921/35359205-17cf812e-0151-11e8-84c4-a90f630318b7.png)
![mobile browser](https://user-images.githubusercontent.com/35746921/35359206-17f3b620-0151-11e8-95ee-f8eb97a656e1.jpg)

**Comment by chalkandmoss** [comment]
For Tall Plant Stand (see screenshots above) I just added new images and replaced the variable images plus added another final image to the gallery to see how that affected the facebook shop. The image has now been replaced in the facebook shop with the FIRST of the new variable images (sycamore), not the last image added to the GALLERY. I was surprised that it wasn't the LAST of the new variable images, as in another Github ticket it was found that the price stated in the facebook shop is the last added price in woocommerce. A variable image is very specific and very different to the feature image. I put a lifestyle image as the feature image, and a detailed image or cutout for the variable. So the lifestyle image (feature) should show. When do you think this might be solved (to be the same as the browser on the iPhone)? Thank you so much!

**Comment by evenmed** [comment]
Same issue here, would like the images shown to be the featured image or to be able to manually choose it after import.

**Comment by mengyingdu** [comment]
Hi @chalkandmoss and @evenmed ,

When you say 'feature image', do you mean you set it as image under variant section? See screen shot: 
![variant feature image](https://user-images.githubusercontent.com/24535640/35638096-0c48d0de-066b-11e8-9a63-7491b0d5c213.jpeg)
We should support to use this image as the one when you pick one variant options. If so, this could be a bug.

Thanks.

**Comment by evenmed** [comment]
What I mean is that it would be best if the product **thumbnail** on facebook was the **parent product's featured image** on woocommerce, so this one for example:
<img width="1282" alt="captura de pantalla 2018-01-31 a la s 11 45 39" src="https://user-images.githubusercontent.com/26916296/35638625-34507d9a-067d-11e8-8543-cbc7af57a24f.png">

Right now the image used for the thumbnail seems to be the featured image of the last variation:
<img width="1280" alt="captura de pantalla 2018-01-31 a la s 11 49 27" src="https://user-images.githubusercontent.com/26916296/35638661-4cfb24bc-067d-11e8-8c48-48b4605eb995.png">
<img width="894" alt="captura de pantalla 2018-01-31 a la s 11 48 32" src="https://user-images.githubusercontent.com/26916296/35638871-ee589e20-067d-11e8-8f27-687cdc50dcd8.png">

I'm aware of the "Use Parent Image" option in Product Data > Facebook. However, this causes the parent image to be used for all variations too. I just want the parent image to be used as the primary image (so the one that shows in the thumbnail), as showing just one of the variations can be deceiving for users.

In my case, for example, they may think the product is just a leash when they see the thumbnail, when in fact it's a leash + collar set, from which you can choose to buy the leash by itself if you want.

**Comment by dmitridr** [comment]
Hi All,

Thanks for your patience. 
@chalkandmoss are you aware of the "Use Parent Image" option in the product edit page as @evenmed pointed out? This should use the `Featured Image`, as you put it, instead of the variant images.

One other thing that can be tried: if there is a default variant set in Woo, I believe that's the image that will be displayed by default on the main page, you could try setting a default, hitting save, then removing the default and saving. This may preserve the default image on FB.

This may be something that can be solved via the Shops interface to allow editing of which product is displayed @mengyingdu have we passed an FB-specific default image/product as a feature to the shops team? 
Maybe we can also add a checkbox saying 'FB Only Default' for some of the variants to fix this from the plugin side as well.

**Comment by Licto** [comment]
Is there anything new about this? Having the same struggle...
Facebook shop use product variations images at random ... sometimes that is the last variation sometimes the first one.
I tried to change default variation but that didn't have any impact on Fb Shop images.

**Comment by dmitridr** [comment]
Hello @Licto can I ask your version? I tried on my test server with the latest version, and changing the default did nothing so I guess we have a bug.

However, as a temporary workaround, if you delete the product on FB (there's an option on the right hand column) then update the default and save, it should re-create the product on FB with the correct default. At least it does for me on our test shop. Does that work for you?

**Comment by dmitridr** [comment]
Update : The default should be working now.

Regarding the original problem, we build the `Use Parent Image` option for this very case, since there has been no response for a month, I will close this out.

If you are still struggling with this problem, please open a new issue on us and reference this one.

**Comment by Tectract** [comment]
bump, same issue on a shop I just set up, Nov 2019

**Comment by negapo** [comment]
This is still an issue for me, i really cannot understand if this is a bug or a feature, if this is a feature its truly hard to understand the rational for this. We have all variable products on our shop and the main product image is not the main product image from Woo, its a picture from one of the variations. Can anyone help? Thanks

**Comment by fredwatson1111** [comment]
Same problem for me as well. Does anyone know if there a fix for this?
