### ISSUE TITLE
Product Feed Customization

### ISSUE THREAD

**Issue by coccoinomane** [facebookincubator/facebook-for-woocommerce#335]
Hello!
First of all, thanks for developing this plugin: it makes creating a product catalog in FB a breeze.

The plugin covers very well the not-so-easy task of synching product information with Facebook, but it can still be improved on the customization side. In this light, have you considered implementing an interface to allow the user to:

1. Choose which products are synched based on product category and (less importantly) on product attributes and product meta.
2. Map WooCommerce product information (including meta) to Facebook product properties. Ideally this could include conditional mapping and find & replace capabilities.

I consider [WP Product Feed Manager](https://www.wpmarketingrobot.com/) to be a great example of such an interface; you can watch the homepage video to get an idea.

Thank you for your attention,
Guido

**Comment by dmitridr** [comment]
Hello!

Thanks for using our plugin and for writing to us about these potential improvements!
We're definitely interested in making the plugin more customizable in the long term, unfortunately our hands are full with bugs right now. If you or anyone else reading this would like to take a stab at adding such an interface into the plugin, we would gladly welcome your pull request!

Some more detail on the specific features you mentioned:
(1) We have a filter that should enable this functionality, but no UI elements. This is a good idea, I believe it has been requested before, and may not be too complex to build.
(2) This is a bit more complex, but also could be useful for our more advanced users.

I'll keep this open as a feature request for now. If anyone else is interested in this, please comment here and we can prioritize this according to the levels of interest in the community.

**Comment by coccoinomane** [comment]
Thank you @dmitridr for your reply!

Hopefully somebody more frontend-savvy than me will step up to the challenge :-)

I agree that the category filter is easier to implement; at the simplest level it can just mimick the standard WordPress multi–checkbox input (see first image below). The next level would be for the category filter to be paired with the category mapping, like it is done by [WP Product Feed Manager](https://www.wpmarketingrobot.com/) (see second image below).

Cheers,
Guido

## WordPress multi–checkbox input
![wordpress-category-choice](https://user-images.githubusercontent.com/3920436/37657012-127bd30c-2c4a-11e8-8151-135c8fcbca17.png)

## Category Filter & Mapping
![wp-product-feed manager](https://user-images.githubusercontent.com/3920436/37657182-8d29a714-2c4a-11e8-98db-a72242d4886f.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by stackedsax** [comment]
@lgfogle this is still an issue.  I'm on version 1.10.2 and created a new catalog last night and still find the 'google_product_category' empty.
